@id=2
PATCH http://localhost:8080/employees
Content-Type: application/json

{
    "id": "{{id}}",
    "firstName": "Eslam",
    "lastName": "Allam",
    "dateOfBirth": "2000-01-01",
    "salary": "7000",
    "joinDate": "2023-05-18",
    "departement": "Support"
}
